# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a3bf1882e983d8a84a45d23f5f8ef30601adedc1783a26eb3016c552f1fd9648c8b96b7b5bbaac07cd9c48dfc4e19140193ce80686942ea18ac669ba024d783

test:
  secret_key_base: 6d06e19894c31271396c6e9cd50cec24e66dbd0d2bc65e18e5f319d174d0381b82ab5101a82ff526523857e1a6f0fd8dad1a9d62c3438c3d92fc2f670d601096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
